### ISSUE TITLE
GLB Models

### ISSUE THREAD

**Issue by Seeingred0** [diarmidmackenzie/instanced-mesh#2]
Hi! Does this instanced mesh component work when feeding it glb / gltf models? I am trying to replace the sphere example with feeding it 3d models.

**Comment by diarmidmackenzie** [comment]
From a quick test, it doesn't seem to work.  I'm not sure why.  I'll take a look and see if I can understand what the problem is.

**Comment by Seeingred0** [comment]
Thanks so much!

**Comment by diarmidmackenzie** [comment]
OK, there seem to be at least a couple of problems here.  The most basic one a sequencing issue - we were trying to add members to the mesh while the GLTF model was still loading.

I've made a fix so these get queued up and applied when the GLTF model is loaded.

https://github.com/diarmidmackenzie/instanced-mesh/commit/1efd28e2b96b38a17595593d4f32adc2c6863981#diff-ed314944982536069e43fca7c67b415cfe06ef1f2ec393491318e1b84cbddc59

With that we can get a basic example working with a GLTF model - see tests/3d-models.htm.

Also a hosted version here:
https://equable-flight.surge.sh/tests/3d-models.htm

One other issue is that the code assumes it will find a "material" for the GLTF model.

Since GLTF models often have built in textures, they won't typically need a material, and if you supply a material, you'll lose the built-in texture info.

So in the example above, I'm using the mesh from the GLTF model, but the textures are overwritten by a black material.  Without the material, it doesn't work.  More investigation needed to figure out whether/how the instanced mesh can keep the original GLTF textures.

**Comment by diarmidmackenzie** [comment]
OK - I have a fix for the materials that works for this GLTF model, and have updated the example to reflect that.

https://github.com/diarmidmackenzie/instanced-mesh/commit/eadaad487c92c52e28f21130240df20f47743c3c#diff-ed314944982536069e43fca7c67b415cfe06ef1f2ec393491318e1b84cbddc59

Hosted demo:
https://quarrelsome-mine.surge.sh/tests/3d-models.htm

The problem is that I have another GLTF model where this isn't working, and I don't know whether that's a specific issue with that specfic GLTF model, or a more general issue.

@Seeingred0  - Can you let me know if this works with the GLTF model you want to use?

**Comment by diarmidmackenzie** [comment]
This is now working with several GLB / GLTF models.  v0.5.0 includes handling models that contain multiple sub-meshes.
